### ISSUE TITLE
Add source code compiling on install

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#13]
For the DHt22/LUX/Rain Gauge - add the source code and compile on install instead of relying on the pre-built binaries.

**Comment by NapaOgden** [comment]
Add echo to screen or progress % when performing an upgrade from system command button.
It's difficult to tell if the upgrade is doing anything.
It would be nice to know if there is a newer version available from the system command screen.
Also add or move installed version display on system command screen

**Comment by rcrum003** [comment]
Both of these are now included in version 1.92.
