### ISSUE TITLE
Fix highcharts to render better on mobile devices

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#16]
Fix yaixis lables to scale for smaller screens

**Comment by rcrum003** [comment]
Yaxis now disappears for trend lines that are not selected.
This is now available in version 1.57 and higher - to get this upgrade, type
sudo /home/HiveControl/scripts/system/checkupgrades.sh
then
sudo /home/HiveControl/upgrade.sh

After getting to 1.57, you can then simply select "Upgrade Code" from the Setttings->System Commands Menu.

**Comment by NapaOgden** [comment]
While the unused axis scales removal is great, I have noticed that the object height appears to be constant (does not scale with screen aspect ratio while the horizontal axis id dynamic and stretches and shrinks.
An example is on a wide screen monitor the dashboard trends are very narrow and long maybe 4 times as wide ans tall (4:1) while on a smart phone in vertical orientation the trends are nearly 1:1 aspic ratio.
I'm wondering if  there is a better way, maybe special code for mobile or some standardized fixed aspic ratio?
