### ISSUE TITLE
Add Save on form selection

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#18]
currently, you have to save an option to see sub options.

**Comment by NapaOgden** [comment]
Which options require saving before submitting options are visible?

**Comment by rcrum003** [comment]
You would have seen them.
When you enable a new instrument, or select a weather source…
If you hit save, then you’ll have other sub options that need to be filled out.

Not a bug, per se, but an annoying feature that requires two save actions..

**Comment by rcrum003** [comment]
Included in Release 1.60 to be posted in a few days.
