### ISSUE TITLE
Time Range Slider Enhancement

### ISSUE THREAD

**Issue by NapaOgden** [rcrum003/HiveControl#19]
Here I go again....
Would it be too much to ask to add the time scale slider as seen on Highstock trend objects?
Is there a better place to add feature requests, I see the catagory but can only find issues entry field?
Ref. http://www.highcharts.com/stock/demo/compare/dark-unica

**Comment by rcrum003** [comment]
Issues and requests can both be put in the issues field..

**Comment by rcrum003** [comment]
After awhile, the slider had to process too much data and doesn't render well in mobile browsers because of the memory.

**Comment by NapaOgden** [comment]
Would a workaround be feasible? 
Maybe only reading & displaying daily average values when the range exceeds some critical size like 60 days so as to limit the processing & memory use?
 I don't think detail would be sacrificed if, considering a screen resolution of perhaps 1366X768 (27% of all web dev).

An example of ten 5 minute samples over 24 hours = 2880 data points X 60 days =17,280 data points read or 1,728 horizontal points per pen imaged.
I'm comparing lines resolution to data points which may be a bad comparison?
1 year would be 10,511 data points if all daily average values were displayed.
How much processing would this involve?

Would this be doable? Is the task too complex for the benefit of flexibility?
I think we need to log midnight to midnight daily averages (mean) anyway.
In this way we can display daily gain/loss, a needed enhancement.

Adrian

**Comment by rcrum003** [comment]
You can currently zoom in, without the sliders, that is already supported..

**Comment by NapaOgden** [comment]
Could day, week, month - backward / forward be easily added

**Comment by rcrum003** [comment]
Also, don't forget, we should be logging into the DB the actual values. Anything like daily average, etc, should be left to code that analyzes the DB. If you look at the detail chart page, we show you daily average and other summary type stats.

**Comment by NapaOgden** [comment]
Good point, are the daily averages derived from 24 hour midnight to
midnight values or the preceding rolling 24 hours?
I suggest midnight to midnight as rolling will differ depending on when
queried.

**Comment by rcrum003** [comment]
This is now supported on HiveControl.org for individual hives.
