### ISSUE TITLE
Dashboard Enhancement - Object placement & content

### ISSUE THREAD

**Issue by NapaOgden** [rcrum003/HiveControl#20]
Consider placing the colorful dashboard last value & detail objects below the trend object.
Organizing the last, min, max, daily change and average values in a color coded (replicate user selected pen colors) in table below the trend object. 
This eliminates continually scrolling down to see the trends (most important & used) when the page loads.

**Comment by rcrum003** [comment]
You are welcome to fork the code and modify that. (easy cut and paste in the Index.php file under pages)
This is a differing of opinion. When i hit the main page, I want to see the current values as quick reference. The charts are secondary to my quick review, and I can see that on my mobile device.

**Comment by NapaOgden** [comment]
Consider adding a conditional link to navigate back to Hivetool web pages if present on the build.
This could be an interim measure while in the development phase.

Add ability to update code manually, I am wondering if the latest revs are being pushed out (NAPAPI5)?

**Comment by rcrum003** [comment]
Two things,
Upgrade Feature is now available 1.57.
For a link to HiveTool, will make a different request and track there.
To get 1.57
This is now available in version 1.57 and higher - to get this upgrade, type
sudo /home/HiveControl/scripts/system/checkupgrades.sh
then
sudo /home/HiveControl/upgrade.sh

After getting to 1.57, you can then simply select "Upgrade Code" from the Setttings->System Commands Menu.
