### ISSUE TITLE
Weight/Slope Wizard

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#23]
Need a wizard that allows a user to set the zero weight from the UI.

Will also need to add a script to pause the collection via Cron, until we configure the slope/intercept.

**Comment by NapaOgden** [comment]
Please expand to be a calibration wizard; include user ability to set a high weight value (stand on scale) so slope can be derived. 
Also need a high user value input for Lux, I use an $25 Chinese handheld Lux meter as a reference. Most (home made) sensor enclosures will have different slopes (gain) settings, Sierra1 needs a X6 multiplier.

**Comment by nanderson77** [comment]
What is the model number of your handheld unit?

**Comment by NapaOgden** [comment]
Actually $14 + $1.29 shipping 3-4% accuracy. Single photo diode, the
TSL2591 has two sensors (wider spectrum) with slightly different response
so they may not equate.
http://www.ebay.com/itm/Digital-Light-Meter-Luminometer-Luxmeter-Photometer-Tester-200000Lux-185806Fc-W/291132563453?_trksid=p2045573.c100507.m3226&_trkparms=aid%3D555014%26algo%3DPL.DEFAULT%26ao%3D1%26asc%3D35375%26meid%3Df8429e441f5c40f3927ea2cdc8065fe6%26pid%3D100507%26rk%3D1%26rkt%3D1%26
Or if that link fails,
Ebay Lux meter
http://pulsar.ebay.com/plsr/clk/0/SADS/9?pld=%7B%22mecs%22%3A%22291132563453f8429e441f5c40f3927ea2cdc8065fe6%22%2C%22enc%22%3A%22AQABAAACYLmQa24OtTHRaocrSZUBEXcLGf4kOqobv9vba2S8XjesUmgDJdZjgQeyIvP899TAdnr8tjKli%2FnkhiZlE712fEbWQyp%2BH54%2Fkf0g6pc0GOa4QzQG0x%2BeMy01oHn0uT3edkd%2BpNqMExf3bCg393Oxvb5cllFWgUX6KLjG%2BxG2SF36EaJYuXbt2ilCtDsMa1xe4oMD80RBXKOyL2%2BzGbkhxQ%2FMoezhEsGNmEth27CV5didaRF2XXU914wdlAKAlwt0jgeamf6kq5Iz73IexQHRU%2BtFge4n8svp04agOGfJsR5WyOzB6DPKD6RzX%2B%2F9ETqcxaH1IfxJ9tZfpPchCUHlNIcQq8%2BMabV10N8LFQblikYCjNrQ0HyXs0h5mUJbTyKb3T6xp5wn5yor9%2BG10xQqx25BhJk%2Fjm3yrnXmwyqfJoh%2FBjys4sNJjeEd1oWii2vpKutC5W0HrFfYpWa8AV8TapPZZIuwx1OOiDX%2FH80zuwwLio4TyYJckoZ6eSrW0zRASTaUTiZs2EhVD%2FKYJZhVPMqGpN2UGQlpF6dOVWT3Dhu3GPB8pER1BB4FTsNKcfuWb6CmwDnzYS5rno9D%2FLQ4ukc3qSJJFg%2Fg5IUPqvpPLzxJeYe7O5kDwyA2bQYGeuxee6xmWod9i1xYmwZ4TShw6BM7rKtAFflpsXDmOB4s8d1deKMeFHVuBHvB%2BcvkoGXy0ZF3IkZJFWOjmCYeniHfq3InvbVjaLWlfqqrpHsNJrqoe%2BEgu98RBQ%2FJA%2BYdXcYAVNY3Tp5ylX%2BzDyZ6OFXOlyU5jLuRNjfnuj8qjRb8U%2FL6%22%7D

**Comment by NapaOgden** [comment]
Weight Sensor Calibration wizard enhancement;
The wizard works well, it would useful if there was a choice to skip zeroing and to skip setting the gain (slope). 
In essence a choice of a single point calibration or two point. Also since the program presumably reads the sensor during calibration, display the weight after it's read, and, or better yet include a weight sensor read button within the wizard similar to the Hivetool read sensors update function.

**Comment by rcrum003** [comment]
In what cases would you skip zeroing the scale? Why wouldn't you always do it together? I think it's an important of that process?

**Comment by NapaOgden** [comment]
I feel it's an advantage to be able to gauge and remove load cell creep.
There is research that attempts to quantify creep, typically 1/2 percent
over a year. It's relatively easy to reset the zero in the field with a
hive on but considerably more difficult to span or set the slope. It's not
that important in relative measurement but more of a concern in absolutes.
It's also helpful in the lab prior to deployment. A bathroom scale is
zeroed before each use as are most certified scales.
Just my two cents worth, not absolutely necessary.
Adrian

**Comment by rcrum003** [comment]
Thanks for the feedback. Makes sense.

How do you set to zero when you have a hive on the scale?

My limited understanding of bathroom scales, it zeros before you get on it.

**Comment by NapaOgden** [comment]
I shim up with a few pieces of wood, ~1"X1"X6", I can send pictures when I
do it,  I use a Octonorm scale frame from Melinda/Thane

**Comment by rcrum003** [comment]
All issues resolved and new feature requests in version 1.80
