### ISSUE TITLE
Default to Zero

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#24]
When an instrument doesn't run, ensure all default to zero, so the charts render, even when a null value.

**Comment by rcrum003** [comment]
Completed with 1.40

**Comment by NapaOgden** [comment]
Ryan,
Awesome, well done!
That's important when/if a sensor fails or gets unplugged for maintenance.
Adrian

**Comment by rcrum003** [comment]
yeah, i’m sure i’ve missed one or two somewhere, but should be able to capture most.
If you see one missing, let me know.
