### ISSUE TITLE
Used rounded numbers in charts

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#26]
In order to smooth out the instrument noise fluctuations.
Float numbers still exist in the database, for precise examination.

**Comment by NapaOgden** [comment]
Here are some ranges to consider. Weight rounded to XXX.XX.
Lux 0-199999 max, temp -50-150F max, humidity 0-100 integer I believe. Could consider having choice of C of F readings. Dunno if this helps.

**Comment by rcrum003** [comment]
Changed all_charts to show rounded numbers, left detail pages with exact numbers.
Will add C or F readings as a different request.
