### ISSUE TITLE
missing xrdp

### ISSUE THREAD

**Issue by nanderson77** [rcrum003/HiveControl#28]
I just installed this posted version, and I'm not able to remote into the raspberry pi.

I ran the following and was able to get remote desktop working again

sudo apt-get install xrdp

**Comment by rcrum003** [comment]
Hmm.. we don’t use XRDP, and don’t install/remove it as part of our build.

We ssh to our servers..

ssh pi@192.168.1.1 mailto:pi@192.168.1.1

**Comment by NapaOgden** [comment]
I / we use XRDP and have shortcuts for Hivetool and HiveControl on the
desktop.
Would be nice if part of the build.

**Comment by nanderson77** [comment]
Paul did add and test it on the previous versioin.  He said it would be part of the default build.

**Comment by rcrum003** [comment]
Ahh, i see, you are commenting on the hivetool image. I'll pass on to Paul at HiveTool.
This is just the base code for the HiveControl portion of the scripts.
