### ISSUE TITLE
Create Config Options for Main Chart

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#34]
Be able to specify which trend lines you want on the front homepage.
This will help reduce the amount of side space that is taken for trends that aren't used.

Alternatively, see if we can configure highcharts to on show Labels when trend line is selected.

**Comment by NapaOgden** [comment]
Please bring back hundredths of a pound to the dashboard chart.

**Comment by NapaOgden** [comment]
Change dashboard to display & trend units that have been selected in configuration.
Alternate units selection; pounds / Kilograms, degree C/F (maybe being done).
Lux or Solar radiation w/m2 (don't need both on main trend axis).

**Comment by rcrum003** [comment]
Re: Hundredths of a pound
This is in version 1.47 - There is an option in Settings -> Site Preferences -> Chart - Round. Uncheck this box if you want .00 of a pound.

**Comment by NapaOgden** [comment]
Pls add version ## reading in basic config with option to update, maybe already there?
If so I probably need to manually update?

**Comment by rcrum003** [comment]
Already have a story to do this. will do this soon.

**Comment by rcrum003** [comment]
This whole thread has been completed. Included in version 1.57
This is now available in version 1.57 and higher - to get this upgrade, type
sudo /home/HiveControl/scripts/system/checkupgrades.sh
then
sudo /home/HiveControl/upgrade.sh

After getting to 1.57, you can then simply select "Upgrade Code" from the Settings->System Commands Menu.
