### ISSUE TITLE
Hivetool Link for People Running Both 

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#35]
Even though we don't expect people to use both sets of tools (old and new), we should make a link back to folks who like to install both..

**Comment by NapaOgden** [comment]
Yes a BIG vote for this!!
Another nice touch is adding desktop shortcuts to Hive Control & Hivetool local hosts and websites with their associated icons.

**Comment by NapaOgden** [comment]
Add ability to change login & authentication, useful when an image file is used for distribution or when cloning systems. Could login be hive name?

**Comment by rcrum003** [comment]
Closing top issue. We don't plan on supporting both interfaces. We are going to deprecate the old version in favor of a new UI. Please submit all the things you loved about the old UI.

**Comment by NapaOgden** [comment]
A few questions; presumably combining the local databases as well as the UI?
Presumably the HiveControl UI will be expanded to include the requisite features from HiveTool?
Or it it the intent to start with a fresh UI look and keep the underlying HiveControl UI code, that would seem to make sense? I'll make a wishlist, also can we copy this infomation to the Hivetool Forums so all are informed?
