### ISSUE TITLE
HiveControl on the Web

### ISSUE THREAD

**Issue by NapaOgden** [rcrum003/HiveControl#36]
Please consider adding HiveControl Dashboard Trend Screens (Highcharts) to allow online web access, reading Hivetool database in cloud. The existing method using port forwarding can be difficult, we need another way to visualize the data in the public domain.
Access from Hivetool website as an alternate to the existing trends.
If possible replicate styles from local Pi development hopefully making updates easier and consistient.
By default perhaps the trends could display all sensors with non null values in the database data file so going from hive to hive may display different pens (sensors).
Use a pick drop-down selection object like Hivetool online employs showing all the active hives one could select. Color coded status would be a nice touch.

**Comment by NapaOgden** [comment]
Requesting development status update for Hivetool 2.0 in the cloud for lack of a better name.
Maybe this is not the right forum?
Some key areas, anything happening, priority?
 Hive Monitor Registration & Testing
 Data Repository structure
 Data Upload & Access
 User Interface
 Chart Graphics

**Comment by rcrum003** [comment]
We now support Registration/Data Upload/Chart Graphics and Configuration backup/sync with local hives on hivecontrol.org.
