### ISSUE TITLE
weather forecast in °C

### ISSUE THREAD

**Issue by mimquadrat** [rcrum003/HiveControl#38]
Hi Sir,
I am from Germany and love your tool! 
Would it be possible to also switch the Underground Forecast to °C instead of °F?
Thank you!

Martin

**Comment by rcrum003** [comment]
Martin, good idea - we'll add to our next release in a few days.

**Comment by rcrum003** [comment]
Ok, was bored while drinking coffee this morning - 
If you hit the upgrade button in the Settings -> System Command (I assume you are running 1.62 or higher).
We now support C in all weather outputs. 1.65 release just released this morning.

**Comment by mimquadrat** [comment]
Hi Ryan!
WOW - great and quick job :)

one more thing (i hope you don’t think i´m a fool):
In the metric view of the temperature there is the symbol ° missing. 
so instead of only C it should be °C (i know it is a little bit hyper precision…but perhaps you know….perhaps only the germans…. :)

and one more thing - I´d love to do the bee tracking (how many go in and out etc) but I can’t find a start.
can you tell me where it is described how to install the camera and what i have to activate in hive control…THANKS!!
(we just booked our holiday in the USA!!! :) CALI we are coming!
