### ISSUE TITLE
no sensor values since last update

### ISSUE THREAD

**Issue by mimquadrat** [rcrum003/HiveControl#42]
from the DHT22 sensors there are no values shown since the last update.

**Comment by rcrum003** [comment]
Can you show us what your Logs are saying:

In the UI - System Commands, there should be some log entries.

**Comment by mimquadrat** [comment]
I tried it with a Raspi 2 and 3 and with the bundle (hivecontool) and just with your github version. 
The bundle works until I perform an update and your github version doesn’t work for me since a week or so.

Log: DHT22 Failed reading GPIO 2

but it worked without touching the wires or doing something else (I checked it with the bundle version).

> Am 31.05.2016 um 21:52 schrieb Ryan notifications@github.com:
> 
> Can you show us what your Logs are saying:
> 
> In the UI - System Commands, there should be some log entries.
>

**Comment by mimquadrat** [comment]
made the update in the bundle to 1.67.
now: 
DHT22 Lock File is in use, retrying
INFO Failed reading GPIO 2: Retried 11 times

**Comment by rcrum003** [comment]
Do the following for this version:

sudo service beecounter stop

We are working through a conflict in the dht22 code…
We have a fix that is in testing now.

Ryan

**Comment by mimquadrat** [comment]
Hi Ryan,
after performing an update to the latest version HiveConTool is not starting anymore.
BTW: You are doing a fantastic job - please include "Donate Button"!

**Comment by rcrum003** [comment]
What version are you on?
Look at Site Settings, first row for the number.

**Comment by mimquadrat** [comment]
I can´t enter anymore - the website is not loading unfortunately.
Also some reboots didn’t help.

> Am 04.06.2016 um 17:59 schrieb Ryan notifications@github.com:
> 
> What version are you on?
> Look at Site Settings, first row for the number.
> 
> Sent from my iPhone
>

**Comment by rcrum003** [comment]
Are you using DHCP?
Can you access the hive via SSH?

**Comment by mimquadrat** [comment]
I use DHCP 
I can acces via SSH (made the reboots via SSH)

**Comment by rcrum003** [comment]
What error message do you get?
Is Apache running?

**Comment by mimquadrat** [comment]
what commandos should I send via SSH to get the error messages?

> Am 04.06.2016 um 20:28 schrieb Ryan notifications@github.com:
> 
> What error message do you get?
> Is Apache running?
> 
> Sent from my iPhone
>

**Comment by rcrum003** [comment]
What error page when you go to your browser?

**Comment by mimquadrat** [comment]
no connection to server

> Am 04.06.2016 um 22:49 schrieb Ryan notifications@github.com:
> 
> What error page when you go to your browser?
>

**Comment by rcrum003** [comment]
Run the following commands and send me the output from SSH

sudo netstat -an |grep LISTEN
sudo ps -ef |grep apache
sudo crontab -l
ls /home
ls -lsa /home/HiveControl/data
cat /etc/apache2/sites-enabled/000-default.conf

**Comment by mimquadrat** [comment]
pi@NAPAPi5:~ $ sudo netstat -an |grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN  
tcp        0      0 0.0.0.0:8888            0.0.0.0:\*               LISTEN  
tcp6       0      0 :::22                   :::\*                    LISTEN  
unix  2      [ ACC ]     STREAM     LISTENING     7695     /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     6423     /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     LISTENING     2032     /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     6426     /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     9272     /tmp/ssh-6uvGHzdT0yno/agent.380
unix  2      [ ACC ]     STREAM     LISTENING     2031     @/tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     4734     /run/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     4756     /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     4760     /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     5938     /tmp/.pcmanfm-socket--0-pi
unix  2      [ ACC ]     STREAM     LISTENING     8741     /tmp/.menu-cached-:0-pi
unix  2      [ ACC ]     STREAM     LISTENING     8599     @/tmp/dbus-Vp4v3sfIqk
unix  2      [ ACC ]     STREAM     LISTENING     5933     /tmp/ssh-pTkYGTlFfJYs/agent.441
unix  2      [ ACC ]     STREAM     LISTENING     7410     /var/run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     LISTENING     7412     /var/run/dhcpcd.unpriv.sock
pi@NAPAPi5:~ $ sudo ps -ef |grep apache
pi       19229 19182  0 14:08 pts/0    00:00:00 grep --color=auto apache
pi@NAPAPi5:~ $ sudo crontab -l

# Edit this file to introduce tasks to be run by cron.

# 

# Each task to run has to be defined through a single line

# indicating with different fields when the task will be run

# and what command to run for the task

# 

# To define the time you can provide concrete values for

# minute (m), hour (h), day of month (dom), month (mon),

# and day of week (dow) or use '*' in these fields (for 'any').#

# Notice that tasks will be started based on the cron's system

# daemon's notion of time and timezones.

# 

# Output of the crontab jobs (including errors) is sent through

# email to the user the crontab file belongs to (unless redirected).

# 

# For example, you can run a backup of all your user accounts

# at 5 a.m every week with:

# 0 5 \* \* 1 tar -zcf /var/backups/home.tgz /home/

# 

# For more information see the manual pages of crontab(5) and cron(8)

# 

# m h  dom mon dow   command

# HiveTool Cron Scripts

# Check the server status. Kill process after 1 minute.

4,9,14,19,24,29,34,39,44,49,54,59 \* \* \* \* timeout -s KILL 1m /home/hivetool/server_status.sh > /var/www/html/server_status.txt

# Check hive instruments every 5 minutes. Kill process after 3 1/2 minutes.

0,5,10,15,20,25,30,35,40,45,50,55 \* \* \* \* timeout -s KILL 3.5m /home/hivetool/hive.sh

#HiveControl Cron Scripts
#Check Sensors every 5 Minutes
1,6,11,16,21,26,31,36,41,46,51,56 \* \* \* \* /home/HiveControl/scripts/system/currconditions.sh > /dev/null 2>&1

#*/5 \* \* \* \* /home/HiveControl/scripts/system/currconditions.sh > /dev/null 2>&1
#Get GDD Data Daily
00 12 \* \* \* /home/HiveControl/scripts/weather/gdd/get_daily_insect_gdd.sh > /dev/null 2>&1

#Check for HiveControl Updates
05 12 \* \* \* /home/HiveControl/scripts/system/checkupgrades.sh > /dev/null 2>&1

#Get Pollen Count Daily
00 12 \* \* \* /home/HiveControl/scripts/weather/pollen/getpollen.sh > /dev/null 2>&1

#Check Message queue once a minute
*/1 \* \* \* \* /home/HiveControl/scripts/system/msgqueue.sh > /dev/null 2>&1

#Get System Status
*/5 \* \* \* \* timeout -s KILL 1m /home/HiveControl/scripts/pimonitor/server_status.sh > /home/HiveControl/www/public_html/admin/server_status.txt
@reboot           /usr/local/bin/pigpiod
pi@NAPAPi5:~ $ ls /home
downloads      hardware      HiveControl  hivetool_20160421  hivetool.zip  pi
downloads.zip  hardware.zip  hivetool     hivetool2.old      old_logs
pi@NAPAPi5:~ $ ls -lsa /home/HiveControl/data
total 13368
   4 drwxr-xr-x  2 www-data www-data    4096 Jun  4 12:05 .
   4 drwxr-xr-x 10 root     root        4096 Jun  4 08:33 ..
   4 -rw-r--r--  1 root     root           3 Jun  4 08:33 DBVERSION
6676 -rwxr-xr-x  1 root     root     6833152 Jun  4 08:33 hive-data.bckup
6676 -rwxr-xr-x  1 www-data www-data 6833152 Jun  4 12:05 hive-data.db
   0 -rw-r--r--  1 root     root           0 Apr  1 12:01 result.txt
   4 -rw-r--r--  1 root     root         280 Apr  1 12:01 syncme.sql
pi@NAPAPi5:~ $ cat /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:80 *:8080>
    # The ServerName directive sets the request scheme, hostname and port that
    # the server uses to identify itself. This is used when creating
    # redirection URLs. In the context of virtual hosts, the ServerName
    # specifies what hostname must appear in the request's Host: header to
    # match this virtual host. For the default virtual host (this file) this
    # value is not decisive as it is used as a last resort host regardless.
    # However, you must set it for any further virtual host explicitly.
    #ServerName www.example.com

```
ServerAdmin webmaster@localhost
DocumentRoot /var/www/html

#To enable multiple sites on port 80
ProxyRequests Off
ProxyPreserveHost On
<Proxy *>
    Require all granted
</Proxy>

    ProxyPass /hivecontrol http://127.0.0.1:81/
    ProxyPassReverse /hivecontrol http://127.0.0.1:81/

ProxyPass /pages http://127.0.0.1:81/pages/
ProxyPassReverse /pages http://127.0.0.1:81/pages/

    ProxyPass /includes http://127.0.0.1:81/includes/
    ProxyPassReverse /includes http://127.0.0.1:81/includes/

    ProxyPass /images http://127.0.0.1:81/images/
    ProxyPassReverse /images http://127.0.0.1:81/images/

    ProxyPass /bower_components http://127.0.0.1:81/bower_components/
    ProxyPassReverse /bower_components http://127.0.0.1:81/bower_components/

ProxyPass /dist http://127.0.0.1:81/dist/
    ProxyPassReverse /dist http://127.0.0.1:81/dist/

    ProxyPass /js http://127.0.0.1:81/js/
    ProxyPassReverse /js http://127.0.0.1:81/js/

    ProxyPass /admin http://127.0.0.1:81/admin
    ProxyPassReverse /admin http://127.0.0.1:81/admin

<Location /hivecontrol>
    Require all granted
</Location>

# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the loglevel for particular
# modules, e.g.
#LogLevel info ssl:warn

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

# For most configuration files from conf-available/, which are
# enabled or disabled at a global level, it is possible to
# include a line for only one particular virtual host. For example the
# following line enables the CGI configuration for this host only
# after it has been globally disabled with "a2disconf".
#Include conf-available/serve-cgi-bin.conf
```

</VirtualHost>

<VirtualHost *:81>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

```
    ServerAdmin webmaster@localhost
    DocumentRoot /home/HiveControl/www/public_html


<Directory />
    Options FollowSymLinks
    AllowOverride None
</Directory>

<Directory /home/HiveControl/www/public_html>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Require all granted
</Directory>

<Directory "/home/HiveControl/www/public_html/admin">
            Options FollowSymLinks
            AllowOverride None
    AuthType Basic
    AuthName "Restricted Content"
    AuthUserFile "/home/HiveControl/www/.htpasswd"
    Require valid-user
</Directory>

# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
    # error, crit, alert, emerg.
    # It is also possible to configure the loglevel for particular
    # modules, e.g.
    #LogLevel info ssl:warn

    ErrorLog ${APACHE_LOG_DIR}/hivecontrolerror.log
    CustomLog ${APACHE_LOG_DIR}/hivecontrolaccess.log combined

    # For most configuration files from conf-available/, which are
    # enabled or disabled at a global level, it is possible to
    # include a line for only one particular virtual host. For example the
    # following line enables the CGI configuration for this host only
    # after it has been globally disabled with "a2disconf".
    #Include conf-available/serve-cgi-bin.conf
```

</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

pi@NAPAPi5:~ $ 

> Am 04.06.2016 um 23:07 schrieb Ryan notifications@github.com:
> 
> cat /etc/apache2/sites-enabled/000-default.conf

**Comment by rcrum003** [comment]
Looks like Apache isn't starting for some reason.

Run this and tell me the output.

sudo service apache2 start

**Comment by mimquadrat** [comment]
pi@NAPAPi5:~ $ sudo service apache2 start
Failed to start apache2.service: Unit apache2.service failed to load: No such file or directory.

> Am 04.06.2016 um 23:47 schrieb Ryan notifications@github.com:
> 
> sudo service apache2 start

**Comment by rcrum003** [comment]
Something has happened to your Apache install..

Is this the Hivetool .7.3 image or is it purely a HIveControl install (where you installed Raspian Jessie and ran ./install.sh)…

**Comment by mimquadrat** [comment]
Image 

> Am 05.06.2016 um 03:31 schrieb Ryan notifications@github.com:
> 
> Something has happened to your Apache install..
> 
> Is this the Hivetool .7.3 image or is it purely a HIveControl install (where you installed Raspian Jessie and ran ./install.sh)…
>

**Comment by mimquadrat** [comment]
I took now a new Raspberry 3 and installed a fresh jessie.
I expanded the file system and updated and upgraded.
I installed via SSH a Hivecontrol (github).

Right now i have version 1.67 and can´t update. It just says:
Waiting on Message Queue Engine to start upgrade job # 1 (could be up to one minute)…
No matter how often I klick on update. 

Underground connection works the DHT22 doesnt (I checked the pinout and used different sensors).

Do you see a possibility to put a working image online?
Ideal would be, if the installed drivers for the Temperhum sensor would already be installed…

Greets Martin!

> Am 05.06.2016 um 03:31 schrieb Ryan notifications@github.com:
> 
> Something has happened to your Apache install..
> 
> Is this the Hivetool .7.3 image or is it purely a HIveControl install (where you installed Raspian Jessie and ran ./install.sh)…
>

**Comment by rcrum003** [comment]
Yes, I’ll work on an image.
Give me a week or so to get it sorted.

**Comment by mimquadrat** [comment]
brillant! 
thank you!
Please include the donate button

> Am 05.06.2016 um 15:02 schrieb Ryan notifications@github.com:
> 
> Yes, I’ll work on an image.
> Give me a week or so to get it sorted.
>

**Comment by rcrum003** [comment]
Actually,
Now as I research it, having people download a large image is not cost effective.

the Upgrade from 1.67 to 1.72 is quite large and will take awhile…( I would like to understand what is going on with your machine, send me your email and we can communicate offline)

If you installed a brand new version, within the past few days, you should have gotten 1.71 or 1.72 right off the bat.

If I make an image to download, I would select Jessie Lite, for the size considerations, but then would get complaints it didn’t have a GUI or was missing minecraft or some other software that I don’t run on my own hives.

Offering an install script is the most efficient way to get installed (as it also doesn’t require us to continually support an image, which creating takes time).

Also, various settings like hostname, root password, pi password, timezone can all be set by the user on install..

If Adrian is monitoring this thread, maybe he can make an image.

(Note, i never use images, and I’m up to 7 Hives with the software, all installed via the script)…

Ryan

**Comment by mimquadrat** [comment]
Hi Ryan,
my Email is :
martin:at:mehringer.eu

from my perspective the script is completely OK, too!
But what is missing (and I think my problems are coming therefore):
A step-by-step instruction. 
Perhaps we can work that out together. Will start and send it to you by mail (if you give me your address).

Should look like this:

download the Jessie.Lite Version: link
put on SD Card with this tool: link
put SD in Raspi 3 (2 works also)
start Raspi
sudo raspi-config
    - expand file system
    - enable camera if you have (buy this it here: link)
etc

> Am 05.06.2016 um 15:14 schrieb Ryan notifications@github.com:
> 
> Actually,
> Now as I research it, having people download a large image is not cost effective.
> 
> the Upgrade from 1.67 to 1.72 is quite large and will take awhile…( I would like to understand what is going on with your machine, send me your email and we can communicate offline)
> 
> If you installed a brand new version, within the past few days, you should have gotten 1.71 or 1.72 right off the bat.
> 
> If I make an image to download, I would select Jessie Lite, for the size considerations, but then would get complaints it didn’t have a GUI or was missing minecraft or some other software that I don’t run on my own hives.
> 
> Offering an install script is the most efficient way to get installed (as it also doesn’t require us to continually support an image, which creating takes time).
> 
> Also, various settings like hostname, root password, pi password, timezone can all be set by the user on install..
> 
> If Adrian is monitoring this thread, maybe he can make an image.
> 
> (Note, i never use images, and I’m up to 7 Hives with the software, all installed via the script)…
> 
> Ryan
>

**Comment by NapaOgden** [comment]
It's my intent to make another HiveConTool image once Hivetool is updated
which should be soon.
This would be a interim solution for the layperson, with instructions.
I favor a unified version, call it Hivetool 2.0 whereby the online
configuration is automated, but I'm not sure if that's a priority?
Currently the online Hivetool configuration is done manually.
