### ISSUE TITLE
Add Icon on Desktop for People who use the desktop

### ISSUE THREAD

**Issue by rcrum003** [rcrum003/HiveControl#43]

**Comment by NapaOgden** [comment]
Please also add an icon to navigate browser to HiveControl / Rcrum003 at Github.
I can give you the shortcut structure if you need it.

I've done two similar links for Hivetool local UI & WebSite on the HiveConTool mashups.

**Comment by rcrum003** [comment]
Closing this out, we don't encourage people to use X/Desktop to manage their hives. We built the webpages to be self sufficient, and with SSH console, you can do most anything. We have been running this code for 3 years now and never had to access the PI desktop...
