### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by mimquadrat** [rcrum003/HiveControl#51]
I have the DHT22 and the TemperHum Sensors.
Question 1: How do I have to wire the DHT22. to 3.3 or 5 V. With a 10kOhm Resistor? 
Question 2: If I want to run the Temperhum Sensor, do I need to install a driver etc first?

**Comment by rcrum003** [comment]
Please see hivetool sensor instructions on hivetool.org

For temperhum, no, HiveControl includes all that you need.

Though, temperhum manufacturer sometimes changes the underlying chip set requiring update of the code.
