### ISSUE TITLE
Date and Time in Dashboard

### ISSUE THREAD

**Issue by mimquadrat** [rcrum003/HiveControl#52]
the Dashboard always shows me: Jan 01, 01:00
I made the settings in raps-config correct (Europe, Berlin), and also the time Zone in Settings (in my case Berlin).

**Comment by rcrum003** [comment]
Are your sensors connected and working - the dashboard shows the last time we had a successful reading..

**Comment by nanderson77** [comment]
Yes sensors are connected and working.

I haven't physically touched the hive for two weeks.

Hivetool.org is still getting updates,

**Comment by rcrum003** [comment]
Nate,
That question was for mimquadrat…

I assume you are still working.

Ryan
