### ISSUE TITLE
Installation from scratch gives Version 1.67

### ISSUE THREAD

**Issue by mimquadrat** [rcrum003/HiveControl#53]
I took a empty SD card and put jessie on it. 
I ran the installation with these commands:
  curl https://raw.githubusercontent.com/rcrum003/HiveControl/master/install.sh -o install.sh
  chmod u+x install.sh
  sudo ./install.sh
Result was a Hivecontrol Version 1.67, but it should be 1.80 if I am not wrong.
Also hitting the update button in the system commands started no update.
(again: please include the donate button! :)

**Comment by rcrum003** [comment]
Hi,
Can you tell me the output of the following commands:
cat /home/HiveControl/VERSION
ls -lsa /home/HiveControl/VERSION

1.67 doesn’t exist anywhere in our repositories.
Are you sure you are connecting to the right PI in your environment?

1.67 was included with the HiveTool Image .7.3 I believe…

Ryan

**Comment by mimquadrat** [comment]
Hi Ryan,
I trippel checked the IP and everything to be sure we are talking about the right pi.
Again. I Took a pi3 made a new SD card with jessie (not lite) on it. 
I installed Hivecontrol with the instructions from Github (incl Beecounter).

running the command from you gave:
pi@raspberrypi:~ $ cat /home/HiveControl/VERSION
1.80
pi@raspberrypi:~ $ ls -lsa /home/HiveControl/VERSION
4 -rw-r--r-- 1 root root 5 Jul 29 11:26 /home/HiveControl/VERSION

checking with the browser gave me Version 1.67 (and yes! really the same IP as with the console).

> Am 30.07.2016 um 19:25 schrieb Ryan notifications@github.com:
> 
> Hi,
> Can you tell me the output of the following commands:
> cat /home/HiveControl/VERSION
> ls -lsa /home/HiveControl/VERSION
> 
> 1.67 doesn’t exist anywhere in our repositories.
> Are you sure you are connecting to the right PI in your environment?
> 
> 1.67 was included with the HiveTool Image .7.3 I believe…
> 
> Ryan
>

**Comment by mimquadrat** [comment]
One more thing:

I installed on an other SD Card the HiveConTool:
https://drive.google.com/open?id=0B8ZWirzPwqHfdGgtRS03RWY3T0E https://drive.google.com/open?id=0B8ZWirzPwqHfdGgtRS03RWY3T0E
I only changed the SD Card, nothing else (the wiring was left as it is)
both, the browser shown version and the version shown in console are 1.57

Both Sensors, DHT22 and Temperhum are working perfectly (not the case with the latest Hivecontrol version from github (1.8 console, 1.67 in browser)

The camera is not working (but works in the 1.8/1.67 Version)

> Am 30.07.2016 um 19:25 schrieb Ryan notifications@github.com:
> 
> Hi,
> Can you tell me the output of the following commands:
> cat /home/HiveControl/VERSION
> ls -lsa /home/HiveControl/VERSION
> 
> 1.67 doesn’t exist anywhere in our repositories.
> Are you sure you are connecting to the right PI in your environment?
> 
> 1.67 was included with the HiveTool Image .7.3 I believe…
> 
> Ryan
>

**Comment by rcrum003** [comment]
Hmm.. Looks like you have the newest version, but the database version column didn't get updated.

Probably because the install script doesn't update that field.

If the file says 1.80, then you are at the latest.

**Comment by NapaOgden** [comment]
I can confirm the same behavior wth install on 2/25/17. The update script does not return anything as before. Versiol is 1.83 but does not report it.
