### ISSUE TITLE
Port conflict with Hivetool

### ISSUE THREAD

**Issue by NapaOgden** [rcrum003/HiveControl#54]
Requesting an installation option to allow HiveControl to coexist with Hivetool on the same system.
Ideally sharing a common database and sensor reads, at a minimum employ a common default index.html page that will branch between Hivetool and HiveControl so a user can select either. If not unified ensure sensor read times are offset.
Hivetool already includes links on each page to jump to HiveControl. 
This is not the ideal solution but failing development coordination should suffice.
This approach should not interfere with standalone installs.

**Comment by rcrum003** [comment]
We no longer support dual installation of Hivetool and HiveControl. If you want to run both, you will need to set that up yourself. HiveControl replicated all functionality of the original hivetool software. We've provided a complete build as well. Future versions (coming soon) will auto register with the hivetool.org central site.
