### ISSUE TITLE
XRDP conflict with RealVnc

### ISSUE THREAD

**Issue by NapaOgden** [rcrum003/HiveControl#55]
XRDP & RealVnc incompatibility affecting XRDP install option.
The latest Pi system updates known as Pixel include RealVnc which breaks XRDP.
The interim fix is to uninstall XRDP, uninstall RealVnc then install XRDP again as follows;
sudo apt-get purge xrdp
sudo apt-get purge realvnc-vnc-server
sudo apt-get install xrdp
There may be a way modify RealVnc config to mitigate the conflict but I have not found a fix which allows both which is preferred. Some (nonwindows) users may prefer RealVnc.
ref. https://www.raspberrypi.org/blog/introducing-pixel/

**Comment by rcrum003** [comment]
I actually recommend that you NOT use RDP to manage your hive. We've written HiveControl to be self sufficient from a simple webpage. If you need more advanced usage, use SSH to login to the console to perform any configurations.
