### ISSUE TITLE
Raspbian OS version comatibiliity?

### ISSUE THREAD

**Issue by NapaOgden** [rcrum003/HiveControl#57]
Has the latest HiveControl version 1.83 been tested with the latest 1/11/17  ver 4.4 of Raspian Jessie lite and with the full Jessie 4.4 Pixel version?
Presumably the LXDE Windows RDP headless (-x) option is not compatible with Pixel due to SW conflicts?
Do the two versions come with other known caveats?

Ref. https://www.raspberrypi.org/downloads/raspbian/

**Comment by NapaOgden** [comment]
Wondering if HiveControl has been tested with Raspbian Stretch version 4.9?
I was unsuccessful in getting it to work, maybe because the desktop shortcuts are missing and instructions limited.  Installation apparently not for the layperson. What's that GUI address again?

**Comment by rcrum003** [comment]
Works with Jessie and now Stretch - We used to specify exact versions, but now just default to the latest version

**Comment by NapaOgden** [comment]
Ryan,
Thank you,
Adrian Ogden
