### ISSUE TITLE
DHT22 not working

### ISSUE THREAD

**Issue by mdebee** [rcrum003/HiveControl#59]
For me querying the DHT22 does not work with HiveControl. The GPIO is set correctly and I can get the data from the sensor using Adafruit, but HiveControl gives "DHT Timeout, make sure you have proper GPIO set returning 0,0 for all values" every time. Is there a solution for this? The query with Adafruit is quite slow as well, so maybe the timeout needs to be increased?

**Comment by rcrum003** [comment]
Can't replicate this issue - we have multiple hives working with the DHT22. Make sure you have the GPIO is set correctly and that it's wired properly.

**Comment by jhaltd** [comment]
This is exactly what I'm seeing - DHT22 works fine using Adafruit, but it times out when polled via HiveControl.  Has this been an open issue since 2018?!
