### ISSUE TITLE
Weather (Outside Temp/Humidity/Solar/Wind, etc) WX key vs hivetool

### ISSUE THREAD

**Issue by ptegler** [rcrum003/HiveControl#61]
hivetool using WX key pulls weather from local weather underground stations works fine under hivetool 0.8.3  hivecontrol using same key(and tested others) does not retrieve anything at all/.  Switching  'outdoors' to second plugged in BME680 sensor pulls data for external but of course does not include rain/wind etc.
hivecontrol change log describes1.9 issues regarding WX.  Can't the code from hivetool be pulled to use as outside data sets to work the same 
(two hives here (3 seperate Pi's / systems) ... hivetool 0.8.3 pulls WX ok, but hivecontrol does not.
Swapped TF cards between Pi's ...testing shows it's not a hardware issue

**Comment by rcrum003** [comment]
Can you please provide more information on what's wrong? What local weather underground station do you have? Also, what version of HiveControl do you have installed 'cat /home/HiveControl/VERSION'

**Comment by ptegler** [comment]
HiveControl is version 1.92-  setting up the same WX site I have under hivetool, reaps no data.  Only when I changed the config to my second BME680 did those 'outside' fields populate with info.
hivetool only asks for station id and a name...hivecontrol asks for a apikey (no idea what that is)

**Comment by rcrum003** [comment]
So when you changed "Weather Source" to "Local Hive Sensors" and selected BME680 - it no longer pulls Rain/Pressure/Lux information or when you select "Weather Source" to "WX Underground" you don't know how to setup a WX API key?

**Comment by ptegler** [comment]
in hivetool, I simply picked a station from the map and entered the ident of that station (not my own station)  hivecontrol is asking for an API key beyond the station ident I'd pulled and am using under hivetool

**Comment by ptegler** [comment]
rdp into my Pi... Hivecontrol and hivetool both running...same station ident entered (no 'api key in hivecontrol'   hive tool is showing WX data with only a station ident entered...hivecontrol show no data
second pi (hive) is strictly running hivtools.... same WX site being used..all data visible without issue (except not being able to use the BME680s.)

**Comment by rcrum003** [comment]
This has been resolved in version 1.93. Please Go to the local hive webpage and navigate to Settings -> System Commands -> Update Code to get the latest version.

**Comment by ptegler** [comment]
upate worked... HC page showed error but returning to app...version in lower left corner was updated to/reads 1.93.  BUT...RAIN parameter read from Weather Underground is showing continuous rain at 999, while other stats are coming through just fine. (only rained this a.m. been sunny since 2pm eastern US

**Comment by rcrum003** [comment]
What weather station id are you using.

**Comment by ptegler** [comment]
kmdsever62

**Comment by ptegler** [comment]
just checked 61 seems off line... KMDMERRI3 and KMDSEVER41 seem fine...will test there

**Comment by ptegler** [comment]
works on 41...can you delete these last couple comments  :-)   also noticed.... index.php
image icons  weight icon has no 'size' (75 pixels)  like the other three
