### ISSUE TITLE
hivecontrol not showing weight in v1.93

### ISSUE THREAD

**Issue by ptegler** [rcrum003/HiveControl#63]
hivecontrol -> calibrate = error    graph is displaying zero weight reading
hivetool is reading weight correctly both in calibrate and in graph

**Comment by rcrum003** [comment]
You really shouldn’t be running both codesets on the same machine at the same time.

What image did you start with?

**Comment by ptegler** [comment]
1.90 (while the screen lower left corner still read 1.6x something.
If the browser page is all that starts the system..they are not running at the same time.
Original install was via dnl, unzip local install... (is how I fixed the co.uk vs me.uk by editing the local copy I installed from.)  Post your fix I did a full install from the script.  Then the update to 1.93 via the systems command page

**Comment by rcrum003** [comment]
the webpage is just a convenient way to see and manage the overall system. The system actually consists of many scripts and cron jobs that over lap with hivetool. You have to commit to one or the other code bases. We support their hardware and the ability to post to their website, in addition to ours. 

The calibrate just helps give you the values. If you have already done it with the Hivetool code, use the same values in the config of HiveControl.

Can you go to a terminal prompt and show us the output of the following commands?

sudo cat /home/HiveControl/VERSION
sudo crontab -l
sudo cat /home/HiveControl/scripts/hiveconfig.inc

**Comment by ptegler** [comment]
yep.. looks like hivetools AND hivecontrol are both running.....

pi@italians:~ $ sudo cat /home/HiveControl/VERSION
1.93
pi@italians:~ $ sudo crontab -l

**Comment by ptegler** [comment]
I have NO idea what that text is that big.... has to be the c-a-p interpreter of something in the cron file

**Comment by ptegler** [comment]
this is the crontab left in place after installing hivecontrol, over the original hivetool image

**Comment by rcrum003** [comment]
Run this command three times and post the results.
/usr/bin/sudo /usr/bin/python /home/HiveControl/scripts/weight/HX711.py

**Comment by ptegler** [comment]
pi@italians:~ $ /usr/bin/sudo /usr/bin/python /home/HiveControl/scripts/weight/HX711.py
5997
pi@italians:~ $ /usr/bin/sudo /usr/bin/python /home/HiveControl/scripts/weight/HX711.py
5979
pi@italians:~ $ /usr/bin/sudo /usr/bin/python /home/HiveControl/scripts/weight/HX711.py
5929
pi@italians:~ $ /usr/bin/sudo /usr/bin/python /home/HiveControl/scripts/weight/HX711.py
-292253
pi@italians:~ $ 

4th time was with 30lbs on it

**Comment by rcrum003** [comment]
If it goes negative, then you might have your load cells installed upside down.

**Comment by ptegler** [comment]
just did a new calibrate (because of the negative numbers) slope and intercept is the same as in hivetool   hivecontrol still returns zero lbs

**Comment by rcrum003** [comment]
What values do you have set for SLOPE/INTERCEPT?

**Comment by ptegler** [comment]
Hivcontrol:
Zero/Intercept   -4.18063
Calibration/Slope   -0.00009954830

Hivetool:
Slope  -0.00009954830
Intercept   -4.18063

all arrows are pointing down

**Comment by ptegler** [comment]
think it's fixed now!
trying to the calibrate wizard was causing a reboot!
I edited the crontab to comment out the hivetool... I noticed the pgio was using different paths (different files?)  so commented that out at the top of the file and left the load at the bottom of the crontab.
re-ran cal.... zero = 4961   slope now at  -9329.6875 (big difference from above post)
back in app... scale now reads the weight I have siting on it!

**Comment by ptegler** [comment]
suggestion.... comment (somewhere) that hivecontrol can no longer reside alongside hivetools orig installation.... and rewrite the cron files (as possible) or use the same path/version of the pigpiod file
hivetool was using /usr/local/bin/pigpiod
hivecontrol is using  usr/bin/pigpiod

**Comment by rcrum003** [comment]
We will write a script that over a certain version, we will comment out hivetool crontab.

BTW, we still send our data to hivetool.org <http://hivetool.org/>, so they aren’t losing anything.

Thanks for the suggestion.

**Comment by ptegler** [comment]
thanks for putting up with me  :-)  I'm fairly experienced (well VERY... 35+ years of coding and electronics design) I think the lack of 'flow' info as to how this is all laid out (same for hivetool) that is causing most of my issues. thanks again for all your work here!

**Comment by rcrum003** [comment]
Going to close this out, since you have it working now.
