### ISSUE TITLE
reduce screen real estate of Y axis labels and retain sleceted traces on refresh

### ISSUE THREAD

**Issue by ptegler** [rcrum003/HiveControl#67]
mobile graph view is all but nil with 6+ traces active, due to y axis label space usage. suggest simplifying the vertical axis by adjusting all traces to scale to 0-100 (reduces number of labels needed like on hivetool).
turning off a trace via (clicking the legend ident) does allow viewing but upon next update they all reappear. Otherwise have to go to setup just to temporarily turn off stuff to view a reduced trace set

**Comment by rcrum003** [comment]
ptegler, this isn't a mobile first platform. You are free to modify the code to suit your needs. Disabling refresh is easy, but for the majority of our users, they will have multiple tabs open on many hives and it was a requested feature to have a refresh at regular intervals. You can also use "detail view" where the relevant data is grouped together. If you are doing deeper analysis, we recommend using a web browser.

**Comment by ptegler** [comment]
have never used HC on a mobile device my request was PC browser only.  Refresh issue was restting what was turned off...refresh ignores settings.
