### ISSUE TITLE
Support bme280 sensors for Temp and Humidity

### ISSUE THREAD

**Issue by DaveyRance** [rcrum003/HiveControl#69]
Any chance in adding in the support for the bme280 sensors for in hive temp / humidity. Amazon has them for about $3 each and i don't think that we need the gas sensors in the hive. (Would reduce the power usage when running on battery.)

For the sensor i found this github module and compiled it and it reads perfectly.
https://github.com/andreiva/raspberry-pi-bme280

Thanks

**Comment by rcrum003** [comment]
Already supported.
Should be in the drop down.

**Comment by DaveyRance** [comment]
On the HiveControll.org and local web interface this is what i see for the supported list of Temp sensors.

TemperHum, Temper, DHT22, DHT21, SHT31-D, BME680

in the temp scripts folder here is what i see for the list of scripts
bme680.sh  dht21.sh  dht22.sh  gettemp.sh  sht31-d.sh  temperhum.sh  temper.sh  temper_test.sh

This is 1.98

**Comment by rcrum003** [comment]
Oh, bme280.. I see.
Sure, we can add it.

**Comment by rcrum003** [comment]
Added support in version 1.99 - tested with https://www.amazon.com/gp/product/B07KYJNFMD/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
