### ISSUE TITLE
Unable to get Temperature / humidity from BME680

### ISSUE THREAD

**Issue by DaveyRance** [rcrum003/HiveControl#70]
Fresh install yesterday of buster and then installed from github following the basic install instructions.

Connected a BME680 and configured temp/hum sensors for bme680 set the slope / zero intercept at 0 and 1 per help bubble.

Click on re-read get the following for the value
Temp F, Humidity%, Dew F, Temp C
-17.60

ssh in and manually run the drive and i get the following results.
pi@raspberrypi:/home/HiveControl/software/BME680_driver $ sudo bme680
72.57 22.54 50.29 1002.57 7330
72.61 22.56 50.14 1002.63 10437
72.66 22.59 50.00 1002.61 12902

change to the scripts / temp folder and run the following
pi@raspberrypi:/home/HiveControl/scripts/temp $ sudo ./gettemp.sh
./gettemp.sh: line 14: [: =: unary operator expected
(standard_in) 1: syntax error
(standard_in) 1: syntax error
   -17.60

**Comment by rcrum003** [comment]
Try running the bme script in that folder as well.

**Comment by DaveyRance** [comment]
That works it is just if it is called from the gettemp.sh it seems to not work.
pi@raspberrypi:/home/HiveControl/scripts/temp $ sudo ./bme680.sh
70.1 51.82 52.76 21.1 1010.44 8423

**Comment by DaveyRance** [comment]
Strange after leaving the system powered down for the night to a demo at our bee club this morning it is reading the bme680 correctly. i guess user error :)

**Comment by rcrum003** [comment]
It can take up to 5 minutes to appear in the config files once set from the web GUI.

Currentconditions.sh calls the config scripts each time it runs.

So, if it’s the first time setting it up, running gettemp.sh does take a bit.
