### ISSUE TITLE
Not Reading Temp Sensor

### ISSUE THREAD

**Issue by jhaltd** [rcrum003/HiveControl#73]
I've tried adding a DHT22 sensor to my Raspberry Pi, but I can't get Hivetool to recognize / read it. I've enabled the sensor in Settings, selected DHT22, specified GPIO 4 (I've tried a dozen GPIOs actually), set intercept to 0 and slope to 1. When I click reread I get: Temp F, Humidity%, Dew F, Temp C, null null null null

When I use the example.py script from Adafruit to read the sensor I get:
Last valid input: 2020-04-29 15:30:40.326392
Temperature: 21.8 C
Humidity: 19.5 %

So the sensor is obviously working. What am I doing wrong with Hivetool?

**Comment by rcrum003** [comment]
Hivetool or HiveControl?
Do you have the hivetool interface board or are you hard wiring the sensor?

Ryan

**Comment by jhaltd** [comment]
Hivecontrol, my mistake.  I am hard wiring the DHT22 to my raspberry pi.

**Comment by rcrum003** [comment]
Which pins do are you plugged into and which model raspberry pi do you have

**Comment by jhaltd** [comment]
I'm testing on a 3 B, but my goal is to deploy it on a Zero W.  The DHT22 is currently plugged into pin #2 (+), pin #6 (-) and pin #7 / GPIO4 (out).

**Comment by jhaltd** [comment]
In addition the DHT22 not working it appears as though the WXUnderground lookup isn't working either:

##########################################################
# Starting HiveControl Current Conditions Collection     #
##########################################################
Getting Latest Configurations

We are registered, so do the needful.....
--- Syncing Local Hive Config with hivecontrol.org ---
HiveControl Version was 104
##########################################################
 --- WEIGHT CHECK DISABLED---

##########################################################
 --- GETTING HIVE TEMP ---
Calculated: TEMPF=null, TEMPC=null, HUMI=null

##########################################################
--- Counting Bee Flights ---
IN=0, OUT=0

##########################################################
--- Getting Ambient Weather ---
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 5 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 4 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 4 seconds. 3 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 8 seconds. 2 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 16 seconds. 1 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 72: [: : integer expression expected
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 75: [: : integer expression expected
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 78: [: : integer expression expected
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 81: [: : integer expression expected
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 84: [: : integer expression expected
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 87: [: : integer expression expected
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 90: [: : integer expression expected
(standard_in) 1: syntax error
/home/HiveControl/scripts/weather/wxunderground/getwxxml.sh: line 93: [: : integer expression expected
(standard_in) 1: syntax error
(standard_in) 1: syntax error
KPASAINT4,'', null ,null,0,null,'null','0','null','null','null','null','null','null','0','0','null','null','null','null','0','0','0'

##########################################################
Calculated LUX = 0

##########################################################
--- Getting Air Quality ---
AIR: 2020-04-30 18:02:15,92, 19, 0.90, 1.62, 1.62

##########################################################
--- Storing in the Database ---

--- Sharing with hivecontrol.org ---
Successfully Posted to HiveControl.org
##########################################################
Script Completed
##########################################################

I've tried the following stations KPAWAYNE5, KPAHAVER17, KPANEWTO35, KTTN, KUKT, KPAWAYNE100

**Comment by jhaltd** [comment]
Issue #59 (https://github.com/rcrum003/HiveControl/issues/59), that was opened in 2018 and is now closed is exactly the same thing.  DHT22 works fine from command line using Adafruit, but times out with polled by HiveControl.  Is this still an open issue?

**Comment by jhaltd** [comment]
When I run the Adafruit example.py I get: 

Last valid input: 2020-05-01 00:32:48.313297
Temperature: 21.7 C
Humidity: 9.9 %

When I run /home/HiveControl/software/DHTXXD/DHTXXD -g4 I get:

0 21.7 58.9

So both are getting the same temperature, but the humidity is wildly different.  

Finally, when I run /home/HiveControl/scripts/system/currconditions.sh I get:
 --- GETTING HIVE TEMP ---
Calculated: TEMPF=null, TEMPC=null, HUMI=null

Of course, that's the one that matters because it's populating the data in HiveControl.

**Comment by rcrum003** [comment]
Our code was designed for users who have the HiveTool Interface board. The issue with your setup is that I need to go research what GPIO you should use to connect to your sensor. This is because you are not using the interface board. Also, the adafruit humidity looks more wrong, unless you live in a very arid environment. Give us a few days to get back to  you man.

**Comment by rcrum003** [comment]
First thing - I think you should move PIN 2 to PIN 1 - Using 3V instead of 5V. That may be causing an issue

**Comment by rcrum003** [comment]
Second, if you are plugged into PIN 4 on the actual raspberry PI, then you should specify "7" in the HiveControl Instruments Page - 
See http://wiringpi.com/pins/ was the original PI library we used and we get to the naming convention.

The DHT script will translate WiringPI -> BCM pin numbers.

**Comment by jhaltd** [comment]
Awesome that worked!  Maybe a note on that screen, or in the Wiki, to say use Pin number instead of GPIO.  Thanks for your help.
