### ISSUE TITLE
Broodminder working?

### ISSUE THREAD

**Issue by jhaltd** [rcrum003/HiveControl#75]
I can't seem to get my HiveControl to see/poll my BroodMinder TH recorder.  I've enabled the instrument, selected BroodMinder T/TH as the device, and entered 42:19:4c as the device option but it doesn't seem to read anything. 

When I ssh into the PI and run a bluetooth scan I see it, so I know that it's in range and waiting for HiveControl to poll:

root@censusPi:/home/HiveControl/scripts/beecount# hcitool lescan
LE Scan ...
18:B4:30:EB:A1:C7 N09UT
18:B4:30:D6:10:08 (unknown)
18:B4:30:D6:10:08 Nest Cam
**_06:09:16:42:19:4C (unknown)_**
18:B4:30:50:0B:AE (unknown)
A0:7D:EA:1B:A6:7B (unknown)
A0:7D:EA:1B:A6:7B Se61a4fe200f72968C
4C:FE:48:2B:66:93 (unknown)
18:B4:30:50:0B:AE Nest Cam
0F:01:F0:18:5F:2B (unknown)

Anyone have any ideas?  Thanks,

Dunc

**Comment by rcrum003** [comment]
Try entering the full Id,
As shown in the scan below.

**Comment by jhaltd** [comment]
I entered the full MAC and then went to the system command window to check things (sorry, should have done that the first time too).  Here's what is reported:

2020-05-16 12:00:29 | TEMP | ERROR | Failed to find BroodMinder Device 42:19:4c 06:09:16:42:19:4c,-75,2020-05-16 12:00:30,55,30.3,86.6,59,100
-- | -- | -- | --

When I go back to entering the portion of the MAC that is listed on the Broodminders, and which the Hivecontrol's help would lead you to believe needs to be entered (last 3 octets) nothing is shown in the log.

**Comment by rcrum003** [comment]
I’ll take a look at the code tonight.
In the bee yard most of the day today.

**Comment by rcrum003** [comment]
Try lowercase C or uppercase C (ie, opposite of what you have set now)

**Comment by jhaltd** [comment]
That was it!  Specify the entire bluetooth MAC address and use lowercase (or potentially the case that your system returns from a scan).  Thanks.

**Comment by rcrum003** [comment]
Updated help text to help future users.
